### PR TITLE
Samsung used DefaultBadger since Android 5.1

### PR DESCRIPTION
**Pull request by kun-qian**
@Leo-Lin Please check it out.

### CODE REVIEW

**Comment by leolin310148** [comment]
it would be better to check the version in `SamsungHomeBadger `

**Comment by leolin310148** [comment]
@kun-qian ?

**Comment by kun-qian** [comment]
@Leo-Lin Samsung uses different badgers based on Android OS version. So I check the version in the Badger factory class instead of SamsungImpl class. What's your idea?

**Comment by leolin310148** [comment]
@kun-qian 
I mean that we should check the 
```
if( Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP_MR1) {}
```

inside `SamsungBadger`

**Comment by leolin310148** [comment]
@kun-qian never mind, I already did that in new version. Thanks for your advice!

**Pull request closed without merging**
