### PR TITLE
Specify Activity to be Badged

### PR DESCRIPTION
**Pull request by joaomgcd**
Added ability to specify activity to be badged instead of always selecting the default one. Useful for apps with multiple launcher activities.

### CODE REVIEW

**Comment by McLoo** [comment]
making the activityToBadge optional wouldn't break current implementations...

**Comment by joaomgcd** [comment]
@McLoo no, it wouldn't :) I implemented it in a way that current implementations still work.

**Comment by McLoo** [comment]
@joaomgcd hell yes! sorry, tottaly missed the ` if (activityToBadge == null)` part.
sry :flushed:

**Comment by joaomgcd** [comment]
@leolin310148 any reason why you don't want to include this change? Thanks

**Pull request closed without merging**
