### PR TITLE
Add support for ZTE devices.

### PR DESCRIPTION
**Pull request by kneep**
Signed-off-by: Alvin Cao <alvin.cao@gmail.com>

### CODE REVIEW

**Comment by leolin310148** [comment]
Hi, is it able to add an sample image like other launchers?

**Comment by kneep** [comment]
Yeah, sure. I'll get back soon.

**Comment by kneep** [comment]
Hi leo. A snapshot is added.

**Comment by leolin310148** [comment]
Great! thank you!

**Pull request merged**
