### PR TITLE
support Vivo OPPO & Lenovo

### PR DESCRIPTION
**Pull request by NingSo**
add 
`LenovoHomeBager.java`
`OPPOHomeBader.java`
`VivoHomeBadger.java`

### CODE REVIEW

**Comment by chenzhaoyan** [comment]
how to replace the code?

**Comment by chenzhaoyan** [comment]
what's your wechat?

**Comment by NingSo** [comment]
id  ningpingping

**Comment by pengwei1024** [comment]
@NingSo biggod, juran zai zheli kandao ni

**Comment by leolin310148** [comment]
@NingSo Thanks a lot! Can you add sample images in `Readmd.md` ?

**Comment by NingSo** [comment]
okay，I will add images tomorrow.

**Pull request closed without merging**
